#!/usr/bin/env sh
# frigonpm
# Copyright (C) 2023  Alexandre Szymocha <github.com/Aksamyt>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# check dependencies
all_good=true
for cmd in npm jq; do
  if ! command -v "${cmd}" >/dev/null 2>&1; then
    echo "${cmd} is required to run this script"
    all_good=false
  fi
done
"${all_good}" || exit 1

# check if package.json exists
if [ ! -f package.json ]; then
  echo "package.json: not found"
  exit 2
fi

npm i
[ "$?" -ne 0 ] && exit 3

ls="$(npm ls --json)"
[ "$?" -ne 0 ] && exit 4
echo "${ls}" | jq -e 'has("dependencies")' >/dev/null || exit 0

new="$(jq '
  ["dependencies", "devDependencies", "optionalDependencies", "peerDependencies"] as $deps
  | ($ls.dependencies | map_values(.version)) as $v
  | to_entries
  | map(
      if (.key as $k | any($deps[]; $k == .)) then
        .value |= (to_entries | map(.value = $v[.key]) | sort_by(.key) | from_entries)
      else
        .
      end
    )
  | from_entries
' ./package.json --argjson ls "${ls}"
)"
[ "$?" -ne 0 ] && exit 5

mv package.json .package.json.bak

echo "${new}" > package.json
